-- 1. Find all records where Size is missing AND purchase_amount > 50
SELECT CUSTOMER_ID, SIZE, PURCHASE_AMOUNT, ITEM_PURCHASED
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
WHERE SIZE IS NULL
  AND PURCHASE_AMOUNT > 50;

-- 2. Total purchases grouped by Season, treating NULL as 'Unknown Season.'
SELECT 
    COALESCE(SEASON, 'Unknown Season') AS SEASON,
    COUNT(*) AS TOTAL_PURCHASES
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
GROUP BY COALESCE(SEASON, 'Unknown Season');

-- 3. Count how many customers used each Payment Method, treating NULLs as 'Not Provided.'
SELECT 
    COALESCE(PAYMENT_METHOD, 'Not Provided') AS PAYMENT_METHOD,
    COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
GROUP BY COALESCE(PAYMENT_METHOD, 'Not Provided');

-- 4. Customers where Promo Code Used is NULL AND Review Rating < 3.0
SELECT CUSTOMER_ID, PROMO_CODE_USED, REVIEW_RATING, ITEM_PURCHASED
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
WHERE PROMO_CODE_USED IS NULL
  AND REVIEW_RATING < 3.0;

-- 5. Average purchase_amount per Shipping Type, treating missing purchase_amount as 0
SELECT 
    SHIPPING_TYPE,
    AVG(COALESCE(PURCHASE_AMOUNT, 0)) AS AVERAGE_PURCHASE_AMOUNT
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
GROUP BY SHIPPING_TYPE;

-- 6. Locations with more than 5 purchases AND no NULL Payment Method
SELECT LOCATION, COUNT(*) AS TOTAL_PURCHASES
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
WHERE PAYMENT_METHOD IS NOT NULL
GROUP BY LOCATION
HAVING COUNT(*) > 5;

-- 7. Create Spender Category using CASE
SELECT 
    CUSTOMER_ID,
    COALESCE(PURCHASE_AMOUNT, 0) AS PURCHASE_AMOUNT,
    CASE
        WHEN COALESCE(PURCHASE_AMOUNT, 0) > 80 THEN 'High'
        WHEN COALESCE(PURCHASE_AMOUNT, 0) BETWEEN 50 AND 80 THEN 'Medium'
        ELSE 'Low'
    END AS SPENDER_CATEGORY
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS;

-- 8. Customers with NULL Previous Purchases AND Color is NOT NULL
SELECT CUSTOMER_ID, COLOR, PREVIOUS_PURCHASES
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
WHERE PREVIOUS_PURCHASES IS NULL
  AND COLOR IS NOT NULL;

-- 9. Total purchase_amount by Frequency of Purchases, treating NULL as 'Unknown'
SELECT 
    COALESCE(FREQUENCY_OF_PURCHASES, 'Unknown') AS FREQUENCY_OF_PURCHASES,
    SUM(PURCHASE_AMOUNT) AS TOTAL_PURCHASE_AMOUNT
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
GROUP BY COALESCE(FREQUENCY_OF_PURCHASES, 'Unknown');

-- 10. Count purchases per Category, excluding NULL Category
SELECT CATEGORY, COUNT(*) AS TOTAL_PURCHASES
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
WHERE CATEGORY IS NOT NULL
GROUP BY CATEGORY;

-- 11. Top 5 Locations with highest total purchase_amount
SELECT LOCATION,
       SUM(COALESCE(PURCHASE_AMOUNT, 0)) AS TOTAL_PURCHASE_AMOUNT
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
GROUP BY LOCATION
ORDER BY TOTAL_PURCHASE_AMOUNT DESC
LIMIT 5;

-- 12. Count entries with NULL Color grouped by Gender & Size
SELECT 
    GENDER,
    SIZE,
    COUNT(*) AS NULL_COLOR_COUNT
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
WHERE COLOR IS NULL
GROUP BY GENDER, SIZE;

-- 13. Items where more than 3 purchases had a NULL Shipping Type
SELECT 
    ITEM_PURCHASED,
    COUNT(*) AS NULL_SHIPPING_TYPE_COUNT
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
WHERE SHIPPING_TYPE IS NULL
GROUP BY ITEM_PURCHASED
HAVING COUNT(*) > 3;

-- 14. Count customers per Payment Method with NULL Review Rating
SELECT 
    PAYMENT_METHOD,
    COUNT(*) AS MISSING_REVIEW_RATING_COUNT
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
WHERE REVIEW_RATING IS NULL
GROUP BY PAYMENT_METHOD;

-- 15. Average Review Rating grouped by Category (NULL → 0), only where avg rating > 3.5
SELECT 
    CATEGORY,
    AVG(COALESCE(REVIEW_RATING, 0)) AS AVERAGE_REVIEW_RATING
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
GROUP BY CATEGORY
HAVING AVG(COALESCE(REVIEW_RATING, 0)) > 3.5;

-- 16. Colors missing in at least 2 rows, and the average Age
SELECT 
    COLOR,
    AVG(AGE) AS AVERAGE_AGE
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
WHERE COLOR IS NULL
GROUP BY COLOR
HAVING COUNT(*) >= 2;

-- 17. Create Delivery Speed using CASE + count customers per category
SELECT 
    CASE
        WHEN SHIPPING_TYPE IN ('Express', 'Next Day Air') THEN 'Fast'
        WHEN SHIPPING_TYPE = 'Standard' THEN 'Slow'
        ELSE 'Other'
    END AS DELIVERY_SPEED,
    COUNT(*) AS CUSTOMER_COUNT
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
GROUP BY 
    CASE
        WHEN SHIPPING_TYPE IN ('Express', 'Next Day Air') THEN 'Fast'
        WHEN SHIPPING_TYPE = 'Standard' THEN 'Slow'
        ELSE 'Other'
    END;

-- 18. Customers with NULL purchase_amount AND Promo Code Used = 'Yes'
SELECT *
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
WHERE PURCHASE_AMOUNT IS NULL
  AND PROMO_CODE_USE

-- 19. Max Previous Purchases per Location (NULL→0), only where avg Review Rating > 4.0
SELECT 
    LOCATION,
    MAX(COALESCE(PREVIOUS_PURCHASES, 0)) AS MAX_PREVIOUS_PURCHASES,
    AVG(REVIEW_RATING) AS AVERAGE_REVIEW_RATING
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
GROUP BY LOCATION
HAVING AVG(REVIEW_RATING) > 4.0;

-- 20. Customers with NULL Shipping Type AND purchase_amount BETWEEN 30 AND 70
SELECT 
    CUSTOMER_ID,
    SHIPPING_TYPE,
    PURCHASE_AMOUNT,
    ITEM_PURCHASED
FROM SHOPPING_DB.PUBLIC.SHOPPING_TRENDS
WHERE SHIPPING_TYPE IS NULL
  AND PURCHASE_AMOUNT BETWEEN 30 AND 70;
